spring:
  application:
    name: chat

  thymeleaf:
    cache: false

  data:
    mongodb:
      uri: "mongodb://localhost:27017/chat_db"
      database: chat_db

  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

server:
  port: 2000
  servlet:
    context-path: /chat
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  tomcat:
    uri-encoding: UTF-8

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
